include(${CMAKE_CURRENT_LIST_DIR}/functions.cmake)

set(CMAKE_TOOLS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/tools)
set(CMAKE_PROJ_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/project)
set(CMAKE_SDK_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/tl_zigbee_sdk)
set(TL_CHECK_FW_TOOL ${CMAKE_TOOLS_DIR}/telink_script/tl_check_fw2.exe)

set(TELINK_PROJECT_NAME sampleLight)
set(TELINK_MCU_CORE 8258)
set(TELINK_BOOTLOADER_FILE bootLoader_8258.bin)
set(TELINK_MERGEN_NAME sampleLight_MERGEN)
set(TELINK_TOOLCHAIN_PATH "tc32-elf-")
set(TELINK_LINKER_SCRIPT ${CMAKE_SDK_SOURCE_DIR}/platform/boot/8258/boot_8258.link)
set(TELINK_EQUIP_TYPE ZR)          # ZR, ZC, ZED
set(TELINK_BOOTLOADER_IMAGE 0)      # IS_BOOT_LOADER_IMAGE: 0: Application, 1: BootLoader
set(TELINK_RAMCODE_MAX 0)           # RESV_FOR_APP_RAM_CODE_SIZE
set(TELINK_FW_OFFSET 0x9000)        # APP_IMAGE_ADDR

set(TELINK_COMPILE_DEFINITIONS      # 相关编译宏
    MCU_CORE_8258=1
    MCU_STARTUP_8258=1
    ROUTER=1
    __PROJECT_TL_DIMMABLE_LIGHT__=1
)

check_vars(
    TELINK_EQUIP_TYPE
    TELINK_BOOTLOADER_IMAGE
    TELINK_RAMCODE_MAX
    TELINK_FW_OFFSET
    TELINK_COMPILE_DEFINITIONS
    TELINK_LINKER_SCRIPT
)